---
title: "Some statistics"
author: "Rosie"
date: 2023-10-24
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r, echo=FALSE, message=FALSE}
library(flextable)
library(tidyverse)

```

# Statistics


```{r, echo=FALSE}

dat <- read.csv("~/housing data/housingcost_over30percent.csv")
names(dat) <- c("location", "total", "owner", "renter")
#head(dat)


t1 <- flextable(dat) %>% 
  add_header_row(values = c("Location", "% of households spending 30% or more of income on shelter cost"),
                  colwidths = c(1, 3)) %>%
  set_header_labels(location = "Location", 
                    total = "Total households", 
                    owner = "Owner households", 
                    renter = "Renter households") %>%
  merge_v(part = "header") %>%
  width(width = c(1.5, 1.6, 1.6, 1.6)) %>%
  set_caption(caption = "Percent of households spending 30% or more of income on shelter cost in primary downtowns by tenure, 2021") %>%
  add_footer_lines("Source: Statistics Canada")

print(t1)
```